In [33]:
import numpy as np
import pandas as pd
import sklearn

In [19]:
dataset

date         price  bedrooms  bathrooms  sqft_living  \
0     2014-05-02 00:00:00  3.130000e+05       3.0       1.50         1340   
1     2014-05-02 00:00:00  2.384000e+06       5.0       2.50         3650   
2     2014-05-02 00:00:00  3.420000e+05       3.0       2.00         1930   
3     2014-05-02 00:00:00  4.200000e+05       3.0       2.25         2000   
4     2014-05-02 00:00:00  5.500000e+05       4.0       2.50         1940   
...                   ...           ...       ...        ...          ...   
4595  2014-07-09 00:00:00  3.081667e+05       3.0       1.75         1510   
4596  2014-07-09 00:00:00  5.343333e+05       3.0       2.50         1460   
4597  2014-07-09 00:00:00  4.169042e+05       3.0       2.50         3010   
4598  2014-07-10 00:00:00  2.034000e+05       4.0       2.00         2090   
4599  2014-07-10 00:00:00  2.206000e+05       3.0       2.50         1490   

      sqft_lot  floors  waterfront  view  condition  sqft_above  \
0         7912     1.5           0     0          3        1340   
1         9050     2.0           0     4          5        3370   
2        11947     1.0           0     0          4        1930   
3         8030     1.0           0     0          4        1000   
4        10500     1.0           0     0          4        1140   
...        ...     ...         ...   ...        ...         ...   
4595      6360     1.0           0     0          4        1510   
4596      7573     2.0           0     0          3        1460   
4597      7014     2.0           0     0          3        3010   
4598      6630     1.0           0     0          3        1070   
4599      8102     2.0           0     0          4        1490   

      sqft_basement  yr_built  yr_renovated                    street  \
0                 0      1955          2005      18810 Densmore Ave N   
1               280      1921             0           709 W Blaine St   
2                 0      1966             0  26206-26214 143rd Ave SE   
3              1000      1963             0           857 170th Pl NE   
4               800      1976          1992         9105 170th Ave NE   
...             ...       ...           ...                       ...   
4595              0      1954          1979            501 N 143rd St   
4596              0      1983          2009          14855 SE 10th Pl   
4597              0      2009             0          759 Ilwaco Pl NE   
4598           1020      1974             0         5148 S Creston St   
4599              0      1990             0         18717 SE 258th St   

           city  statezip country  
0     Shoreline  WA 98133     USA  
1       Seattle  WA 98119     USA  
2          Kent  WA 98042     USA  
3      Bellevue  WA 98008     USA  
4       Redmond  WA 98052     USA  
...         ...       ...     ...  
4595    Seattle  WA 98133     USA  
4596   Bellevue  WA 98007     USA  
4597     Renton  WA 98059     USA  
4598    Seattle  WA 98178     USA  
4599  Covington  WA 98042     USA  

[4600 rows x 18 columns]

In [20]:
dataset.pop('street')
dataset.pop('city')
dataset.pop('statezip')
dataset.pop('country')
dataset.pop('view')
dataset.pop('date')

0       2014-05-02 00:00:00
1       2014-05-02 00:00:00
2       2014-05-02 00:00:00
3       2014-05-02 00:00:00
4       2014-05-02 00:00:00
               ...         
4595    2014-07-09 00:00:00
4596    2014-07-09 00:00:00
4597    2014-07-09 00:00:00
4598    2014-07-10 00:00:00
4599    2014-07-10 00:00:00
Name: date, Length: 4600, dtype: object

In [21]:
dataset

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0              0          3        1340              0      1955          2005  
1              0          5        3370            280      1921             0  
2              0          4        1930              0      1966             0  
3              0          4        1000           1000      1963             0  
4              0          4        1140            800      1976          1992  
...          ...        ...         ...            ...       ...           ...  
4595           0          4        1510              0      1954          1979  
4596           0          3        1460              0      1983          2009  
4597           0          3        3010              0      2009             0  
4598           0          3        1070           1020      1974             0  
4599           0          4        1490              0      1990             0  

[4600 rows x 12 columns]

In [22]:
dataset.to_csv('data.csv',index=False)

In [27]:
conditions = [
    (dataset['price'] <= 100000),
    (dataset['price'] > 100000) & (dataset['price'] <= 500000),
    (dataset['price'] > 500000 )]

values = ['lower_class', 'middle_class', 'upper_class']

dataset['society'] = np.select(conditions, values)

In [28]:
dataset

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  condition  sqft_above  sqft_basement  yr_built  \
0              0          3        1340              0      1955   
1              0          5        3370            280      1921   
2              0          4        1930              0      1966   
3              0          4        1000           1000      1963   
4              0          4        1140            800      1976   
...          ...        ...         ...            ...       ...   
4595           0          4        1510              0      1954   
4596           0          3        1460              0      1983   
4597           0          3        3010              0      2009   
4598           0          3        1070           1020      1974   
4599           0          4        1490              0      1990   

      yr_renovated       society  
0             2005  middle_class  
1                0   upper_class  
2                0  middle_class  
3                0  middle_class  
4             1992   upper_class  
...            ...           ...  
4595          1979  middle_class  
4596          2009   upper_class  
4597             0  middle_class  
4598             0  middle_class  
4599             0  middle_class  

[4600 rows x 13 columns]

In [29]:
dataset.to_csv('data.csv',index=False)

In [30]:
dataset

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     3.130000e+05       3.0       1.50         1340      7912     1.5   
1     2.384000e+06       5.0       2.50         3650      9050     2.0   
2     3.420000e+05       3.0       2.00         1930     11947     1.0   
3     4.200000e+05       3.0       2.25         2000      8030     1.0   
4     5.500000e+05       4.0       2.50         1940     10500     1.0   
...            ...       ...        ...          ...       ...     ...   
4595  3.081667e+05       3.0       1.75         1510      6360     1.0   
4596  5.343333e+05       3.0       2.50         1460      7573     2.0   
4597  4.169042e+05       3.0       2.50         3010      7014     2.0   
4598  2.034000e+05       4.0       2.00         2090      6630     1.0   
4599  2.206000e+05       3.0       2.50         1490      8102     2.0   

      waterfront  condition  sqft_above  sqft_basement  yr_built  \
0              0          3        1340              0      1955   
1              0          5        3370            280      1921   
2              0          4        1930              0      1966   
3              0          4        1000           1000      1963   
4              0          4        1140            800      1976   
...          ...        ...         ...            ...       ...   
4595           0          4        1510              0      1954   
4596           0          3        1460              0      1983   
4597           0          3        3010              0      2009   
4598           0          3        1070           1020      1974   
4599           0          4        1490              0      1990   

      yr_renovated       society  
0             2005  middle_class  
1                0   upper_class  
2                0  middle_class  
3                0  middle_class  
4             1992   upper_class  
...            ...           ...  
4595          1979  middle_class  
4596          2009   upper_class  
4597             0  middle_class  
4598             0  middle_class  
4599             0  middle_class  

[4600 rows x 13 columns]

In [34]:
x=dataset.iloc[: , :-1 ].values

In [36]:
y=dataset.iloc[ :, -1].values

In [53]:
from sklearn.model_selection import train_test_split

In [55]:
x_train,x_test,y_train,y_test= train_test_split(x ,y ,test_size=0.4,random_state=0)

In [56]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)



In [57]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred=classifier.predict(x_test)


In [59]:
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[ 24   0   0]
 [  0 990   0]
 [  0   1 825]]


In [60]:
accuracy_score(y_test,y_pred)

0.9994565217391305